### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by siiptuo** [rrrkkk/TiraLabra#1]
Ladattu 22.4.2017 12.20

Työ kääntyy ja tiedoston salaus onnistuu hyvin. En saanut testejä ajettua, koska CUnitin kanssa oli ongelmia.

Yleisesti koodia lukiessa häiritsi, ettei tyyli ole täysin yhteneväinen. Esimerkiksi välissä käytetään tabulaattoria sisennykseen. Ehkä voisit ajaa koodin läpi [clang-format](https://clang.llvm.org/docs/ClangFormat.html) tai [astyle](http://astyle.sourceforge.net/) työkaluista.

Itse AES toteutuksesta on vaikea sanoa mitään. Koodi on hyvin kommentoitu, vaikkei selitäkkään algoritmin toimintaa tarkasti. Tämä ei haittaa, koska se perustuu ja viittaa standardiin.

Käyttöliittymän `do_encrypt` ja `do_decrypt` rakenteessa on mielestäni parannettavaa. Ensinnäkin `n_r_p` ja `n_w_p` eivät ole kovin kuvaavia nimiä. Tämän lisäksi lopuksi ajettavaa koodia voisi siirtää pois `while`-silmukasta korvaten tämän `break`-lauseella. Tällöin funktion normaali suoritus olisi paremmin hahmoteltavissa.

`main`-funktion toiminnallisuutta voisi jakaa useisiin funktioihin etenkin salausavaimen lukemiseen. Tähän liittyen salausavainsyöte käydään aina virheellisesti 32 kertaa läpi, vaikkei sen pituus ole 32. `strlen` on myös osittain turha, koska syöte käydään aina läpi.

**Comment by rrrkkk** [comment]
Kiitos palautteesta, viilaillaan koodia :)
