### ISSUE TITLE
Koodikatselmointi #2

### ISSUE THREAD

**Issue by MatiasLyyra** [rrrkkk/TiraLabra#2]
Projekti ladattu: 22:47 26.04.2017

Ohjelma vaikutti toimivan parilla testitiedostolla kokeillessani. Koodi on hyvin kommentoitu ja erityisesti plussaa viittauksista standardiin, josta voi hyvin lukea lisää koodin toiminnasta. Yksi pintapuolinen asia, joka osui silmään, oli melko pitkät vakiotaulukoiden alustukset aes.c tiedoston alussa. Luettavuuden kannalta nämä voisivat olla omassa tiedostossaan. 

Yksikkötestejä en saanut toimimaan ja gradle antoi virheen ”Plugin with id ’cunit-test-suite’ not found.”.  Päältäpäin katsottuna yksikkötestit vaikuttivat kuitenkin olevan kattavia.

**Comment by rrrkkk** [comment]
Kiitoksia kommenteista. Viilaillaan koodia :)
